# Generated by Django 3.1.4 on 2021-03-03 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosCantones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_cant', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_mpio', models.CharField(blank=True, max_length=10, null=True)),
                ('id_event', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantones', models.CharField(blank=True, max_length=50, null=True)),
                ('evento', models.CharField(blank=True, max_length=50, null=True)),
                ('muertos', models.IntegerField(blank=True, null=True)),
                ('heridos', models.IntegerField(blank=True, null=True)),
                ('desaparecidos', models.IntegerField(blank=True, null=True)),
                ('personas', models.IntegerField(blank=True, null=True)),
                ('familias', models.IntegerField(blank=True, null=True)),
                ('viv_destruidas', models.IntegerField(blank=True, null=True)),
                ('viv_averiadas', models.IntegerField(blank=True, null=True)),
                ('vias', models.IntegerField(blank=True, null=True)),
                ('ptes_vehic', models.IntegerField(blank=True, null=True)),
                ('ptes_peat', models.IntegerField(blank=True, null=True)),
                ('acued', models.IntegerField(blank=True, null=True)),
                ('alcant', models.IntegerField(blank=True, null=True)),
                ('c_salud', models.IntegerField(blank=True, null=True)),
                ('c_educat', models.IntegerField(blank=True, null=True)),
                ('c_communi', models.IntegerField(blank=True, null=True)),
                ('hectareas', models.TextField(blank=True, null=True)),
                ('menajes', models.TextField(blank=True, null=True)),
                ('ap_aliment', models.TextField(blank=True, null=True)),
                ('tejas', models.TextField(blank=True, null=True)),
                ('sacos', models.TextField(blank=True, null=True)),
                ('otros_apoyo', models.TextField(blank=True, null=True)),
                ('economy', models.TextField(blank=True, null=True)),
                ('total', models.TextField(blank=True, null=True)),
                ('apoyos_tramite', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos_cantones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuentesAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_union', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'fuentes_agua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPuntos',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'tabla_puntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('srid', models.IntegerField()),
                ('precision', models.FloatField()),
                ('hasz', models.BooleanField()),
            ],
            options={
                'db_table': 'topology',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('topology', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='PobrezaHM.topology')),
                ('layer_id', models.IntegerField()),
                ('schema_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('feature_column', models.CharField(max_length=50)),
                ('feature_type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('child_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'layer',
                'managed': False,
            },
        ),
    ]
